### ISSUE TITLE
Codelab 'Simulating a Thread network using OpenThread in Docker': unable to run ot-daemon

### ISSUE THREAD

**Issue by j-noel-longhand** [openthread/ot-docs#67] opened 2022-01-10 18:05 UTC
The Docker Thread sim Codelab has a possible issue with running the ot-daemon in container #2 (https://openthread.io/codelabs/openthread-simulation#4).

Initially, the daemon is unable to find the `ipset` command (apparently this is missing from the Docker image). 

Once `ipset` is installed, however, it displays a message that the ip set does not exist:

```
root@162dbab6802a:~/src/openthread# ./output/posix/bin/ot-daemon -v 'spinel+hdlc+forkpty://output/simulation/bin/ot-rcp?forkpty-arg=2'
./output/posix/bin/ot-daemon[170]: Running OPENTHREAD/g442b7e82f; POSIX; Jan  7 2022 05:52:28
./output/posix/bin/ot-daemon[170]: Thread version: 3
./output/posix/bin/ot-daemon[170]: Thread interface: wpan0
./output/posix/bin/ot-daemon[170]: RCP version: OPENTHREAD/g442b7e82f; SIMULATION; Jan  7 2022 05:50:28
ipset v6.34: Kernel support protocol versions 6-7 while userspace supports protocol versions 6-6
The set with the given name does not exist
```
When one runs `ipset list`, no ip sets are listed.

This behavior was observed on two different Debian machines, one running the latest vanilla Debian Stretch.

**Comment by wgtdkp** [comment] 2022-01-11 03:20
@superwhd This seems related to the latest ingress filter feature, will you take a look?

**Comment by superwhd** [comment] 2022-01-11 06:10
Sent a fix: https://github.com/openthread/openthread/pull/7305. This issue was caused by a feature `firewall` that shouldn't have been enabled on ot-daemon. Although enabling it won't break the ot-daemon's behavior, we'd better disable it to avoid such confusing logs.

**Comment by shuhain** [comment] 2022-01-12 09:42
sudo ./build/posix/src/posix/ot-daemon -v     'spinel+hdlc+uart:///dev/ttyACM1?uart-baudrate=115200'
./build/posix/src/posix/ot-daemon[3281]: Running OPENTHREAD/thread-reference-20200818-1443-g55af6ce2c; POSIX; Jan 11 2022 18:04:30
./build/posix/src/posix/ot-daemon[3281]: Thread version: 3
./build/posix/src/posix/ot-daemon[3281]: Thread interface: wpan1
./build/posix/src/posix/ot-daemon[3281]: RCP version: OPENTHREAD/thread-reference-20200818-1436-g442b7e82f; NRF52840; Jan 10 2022 22:39:12
sh: 1: ipset: not found

**Comment by superwhd** [comment] 2022-01-12 09:54
The fix PR has been merged on main branch. I tried the codelab locally and the `ipset` error message doesn't show. I'm closing this bug.

@j-noel-longhand @shuhain Please update your repository/docker image. Let me know if you still see the error.

**Closed by superwhd** 2022-01-12 09:54 UTC
Labels: bug, documentation
